alias c='clear'
alias q='exit'
alias l='ls -Ag --si --group-directories-first --color=auto'
alias a='ag -i -Q'

alias gl='git log'
alias gst='git status'
alias gps='git push -u origin $(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f3)'
alias gpf='git push --force-with-lease origin $(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f3)'
alias gpr='git pull --rebase origin $(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f3)'
alias gct='git add -A && git commit --no-verify -v -m'
alias gco='git checkout'
alias gdf='git diff'
alias grs='git reset --soft HEAD~'
